variable "aws_region" { default = "ap-south-1" }
variable "project_name" { default = "octabyte-nithin" }
variable "environment" { default = "production" }
variable "vpc_cidr" { default = "10.20.0.0/16" }
variable "availability_zone_count" { default = 2 }
variable "public_subnet_cidrs" { default = ["10.20.1.0/24", "10.20.2.0/24"] }
variable "private_app_subnet_cidrs" { default = ["10.20.10.0/24", "10.20.11.0/24"] }
variable "private_db_subnet_cidrs" { default = ["10.20.20.0/24", "10.20.21.0/24"] }
variable "db_username" { default = "appadmin" }
variable "db_instance_class" { default = "db.t3.micro" }
variable "db_allocated_storage" { default = 20 }
variable "db_name" { default = "appdb" }
variable "application_port" { default = 8000 }
variable "health_check_path" { default = "/health" }
variable "alb_enable_deletion_protection" { default = false }
variable "root_volume_size" { default = 20 }
variable "root_volume_type" { default = "gp3" }
variable "enable_detailed_monitoring" { default = false }
variable "asg_min_size" { default = 2 }
variable "asg_max_size" { default = 4 }
variable "asg_desired_capacity" { default = 2 }
variable "target_tracking_target_value" { default = 70.0 }
variable "tags" { default = {
  Project     = "OctaByte-Nithin"
  Environment = "production"
  Owner       = "nithingowdahm87"
  ManagedBy   = "Terraform"
} }
variable "blue_weight" { default = 100 }
variable "green_weight" { default = 0 }
